### ISSUE TITLE
cleanup demo adapter

### ISSUE THREAD

**Issue by pepyakin** [thrumdev/blobs#33]
right now, the demo still mentions celestia adapter in a few places. Here is for example rollup_config.toml

```toml
[da]
# The JWT used to authenticate with the celestia light client. Instructions for generating this token can be found in the README
celestia_rpc_auth_token = "MY.SECRET.TOKEN"
# The address of the *trusted* Celestia light client to interact with
celestia_rpc_address = "http://127.0.0.1:26658"
# The largest response the rollup will accept from the Celestia node. Defaults to 100 MB
max_celestia_response_body_size = 104_857_600
# The maximum time to wait for a response to an RPC query against Celestia node. Defaults to 60 seconds.
celestia_rpc_timeout_seconds = 60
```

we should clean it up
